version: '3.3'
services:
  ortho-planner-db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ortho-planner
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    expose:
      - 8080
  ortho-planner-front:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    working_dir: /myapp
    expose:
      - 3000
    links:
      - ortho-planner-db
    depends_on:
      - ortho-planner-db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=front-${COMPOSE_PROJECT_NAME}"
      - "traefik.frontend.rule=Host:${FRONT_HOST}.${DOMAINNAME}"
      - "traefik.port=${FRONT_PORT}"
      - "traefik.docker.network=${FRONT_PROXY}"
    environment:
      RAILS_ENV: "${RAILS_ENV}"
    networks:
      - traefik_proxy
      - default
networks:
  traefik_proxy:
    external: true