require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InteractionObjectsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # InteractionObject. As you add validations to InteractionObject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InteractionObjectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all interaction_objects as @interaction_objects" do
      interaction_object = InteractionObject.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:interaction_objects)).to eq([interaction_object])
    end
  end

  describe "GET #show" do
    it "assigns the requested interaction_object as @interaction_object" do
      interaction_object = InteractionObject.create! valid_attributes
      get :show, params: {id: interaction_object.to_param}, session: valid_session
      expect(assigns(:interaction_object)).to eq(interaction_object)
    end
  end

  describe "GET #new" do
    it "assigns a new interaction_object as @interaction_object" do
      get :new, params: {}, session: valid_session
      expect(assigns(:interaction_object)).to be_a_new(InteractionObject)
    end
  end

  describe "GET #edit" do
    it "assigns the requested interaction_object as @interaction_object" do
      interaction_object = InteractionObject.create! valid_attributes
      get :edit, params: {id: interaction_object.to_param}, session: valid_session
      expect(assigns(:interaction_object)).to eq(interaction_object)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new InteractionObject" do
        expect {
          post :create, params: {interaction_object: valid_attributes}, session: valid_session
        }.to change(InteractionObject, :count).by(1)
      end

      it "assigns a newly created interaction_object as @interaction_object" do
        post :create, params: {interaction_object: valid_attributes}, session: valid_session
        expect(assigns(:interaction_object)).to be_a(InteractionObject)
        expect(assigns(:interaction_object)).to be_persisted
      end

      it "redirects to the created interaction_object" do
        post :create, params: {interaction_object: valid_attributes}, session: valid_session
        expect(response).to redirect_to(InteractionObject.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved interaction_object as @interaction_object" do
        post :create, params: {interaction_object: invalid_attributes}, session: valid_session
        expect(assigns(:interaction_object)).to be_a_new(InteractionObject)
      end

      it "re-renders the 'new' template" do
        post :create, params: {interaction_object: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested interaction_object" do
        interaction_object = InteractionObject.create! valid_attributes
        put :update, params: {id: interaction_object.to_param, interaction_object: new_attributes}, session: valid_session
        interaction_object.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested interaction_object as @interaction_object" do
        interaction_object = InteractionObject.create! valid_attributes
        put :update, params: {id: interaction_object.to_param, interaction_object: valid_attributes}, session: valid_session
        expect(assigns(:interaction_object)).to eq(interaction_object)
      end

      it "redirects to the interaction_object" do
        interaction_object = InteractionObject.create! valid_attributes
        put :update, params: {id: interaction_object.to_param, interaction_object: valid_attributes}, session: valid_session
        expect(response).to redirect_to(interaction_object)
      end
    end

    context "with invalid params" do
      it "assigns the interaction_object as @interaction_object" do
        interaction_object = InteractionObject.create! valid_attributes
        put :update, params: {id: interaction_object.to_param, interaction_object: invalid_attributes}, session: valid_session
        expect(assigns(:interaction_object)).to eq(interaction_object)
      end

      it "re-renders the 'edit' template" do
        interaction_object = InteractionObject.create! valid_attributes
        put :update, params: {id: interaction_object.to_param, interaction_object: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested interaction_object" do
      interaction_object = InteractionObject.create! valid_attributes
      expect {
        delete :destroy, params: {id: interaction_object.to_param}, session: valid_session
      }.to change(InteractionObject, :count).by(-1)
    end

    it "redirects to the interaction_objects list" do
      interaction_object = InteractionObject.create! valid_attributes
      delete :destroy, params: {id: interaction_object.to_param}, session: valid_session
      expect(response).to redirect_to(interaction_objects_url)
    end
  end

end
